
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoes
  namespaces: dmsng
  labels:
    app: shoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoes
  template:
    metadata:
      labels:
        app: shoes
    spec:
      containers:
      - name: shoes
        image: kanwarsaad/shoes:v8
        ports:
        - containerPort: 3000
